services:
  - type: web
    name: adani-otp-app
    env: python
    buildCommand: ""
    startCommand: gunicorn adani.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: TWILIO_ACCOUNT_SID
        value: ${TWILIO_ACCOUNT_SID}
      - key: TWILIO_AUTH_TOKEN
        value: ${TWILIO_AUTH_TOKEN}
      - key: TWILIO_PHONE_NUMBER
        value: ${TWILIO_PHONE_NUMBER}
